from _typeshed import Incomplete

from ioavstats import glob_local as glob_local
from ioavstats import utils as utils

IO_LAST_SEEN: Incomplete
logger: Incomplete

def download_us_cities_file() -> None: ...
def download_us_zips_file() -> None: ...
def download_zip_code_db_file() -> None: ...
def load_airport_data() -> None: ...
def load_aviation_occurrence_categories() -> None: ...
def load_country_state_data() -> None: ...
def load_sequence_of_events() -> None: ...
def load_simplemaps_data() -> None: ...
def load_zip_codes_org_data() -> None: ...
