LINK_GITHUB_PAGES: str

def get_ae1982_app() -> None: ...
def get_ae1982_bar_chart(chart_id: str, chart_title: str) -> None: ...
def get_pd1982_app() -> None: ...
def get_pd1982_data_profile() -> None: ...
def get_pd1982_details() -> None: ...
