# Copyright (c) 2022-2024 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""
from dynaconf import Dynaconf  # type: ignore
from psycopg2.extensions import connection
from psycopg2.extensions import cursor
from sqlalchemy.engine import Engine

def get_args() -> str: ...
def get_engine(settings: Dynaconf) -> Engine: ...
def get_postgres_connection() -> connection: ...
def prepare_latitude(latitude_string: str) -> str: ...
def prepare_longitude(longitude_string: str) -> str: ...
def present_about(pg_conn: connection, app_id: str) -> None: ...
def upd_io_processed_files(file_name: str, cur_pg: cursor) -> None: ...
