from _typeshed import Incomplete
from dynaconf import Dynaconf as Dynaconf
from psycopg import Connection, Cursor
from sqlalchemy.engine import Engine

logger: Incomplete

def get_args() -> str: ...
def get_engine(settings: Dynaconf) -> Engine: ...
def get_postgres_connection() -> Connection: ...
def prepare_latitude(latitude_string: str) -> str: ...
def prepare_longitude(longitude_string: str) -> str: ...
def present_about(pg_conn: Connection, app_id: str) -> None: ...
def upd_io_processed_files(file_name: str, cur_pg: Cursor) -> None: ...
