from _typeshed import Incomplete
from dynaconf import Dynaconf  # type: ignore
from psycopg2.extensions import connection
from psycopg2.extensions import cursor
from sqlalchemy.engine import Engine

logger: Incomplete

def get_args() -> str: ...
def get_engine(settings: Dynaconf) -> Engine: ...
def get_postgres_connection() -> connection: ...
def prepare_latitude(latitude_string: str) -> str: ...
def prepare_longitude(longitude_string: str) -> str: ...
def present_about(pg_conn: connection, app_id: str) -> None: ...
def upd_io_processed_files(file_name: str, cur_pg: cursor) -> None: ...
