version: '3.3'

volumes:
  portainer_data:
    external: true

services:

  # ------------------------------------------------------------------------------
  # portainer.
  # ------------------------------------------------------------------------------
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data portainer/portainer-ce:latest

  # ------------------------------------------------------------------------------
  # PostgreSQL Database IO-AVSTATS-DB.
  # ------------------------------------------------------------------------------
  io_avstats_db:
    command: postgres -c "max_connections=200"
    container_name: io_avstats_db
    environment:
      - POSTGRES_DB=${IO_AERO_POSTGRES_DBNAME}
      - POSTGRES_PASSWORD=${IO_AERO_POSTGRES_PASSWORD}
      - POSTGRES_USER=${IO_AERO_POSTGRES_USER}
    image: postgres:${IO_AERO_POSTGRES_VERSION}
    ports:
      - ${IO_AERO_POSTGRES_CONNECTION_PORT}:5432
    restart: always
    volumes:
      - ./${IO_AERO_POSTGRES_PGDATA}:/var/lib/postgresql/data

  # ------------------------------------------------------------------------------
  # ae1982 - Aircraft Events since 1982.
  # ------------------------------------------------------------------------------
  ae1982:
    container_name: ae1982
    depends_on:
      - io_avstats_db
    image: ioaero/ae1982:latest
    expose:
      - ${IO_AERO_STREAMLIT_SERVER_PORT}
    restart: always

  # ------------------------------------------------------------------------------
  # pd1982 - Profiling Data since 1982.
  # ------------------------------------------------------------------------------
  pd1982:
    container_name: pd1982
    depends_on:
      - io_avstats_db
    image: ioaero/pd1982:latest
    expose:
      - ${IO_AERO_STREAMLIT_SERVER_PORT}
    restart: always

  # ------------------------------------------------------------------------------
  # slara - Association Rule Analysis.
  # ------------------------------------------------------------------------------
  slara:
    container_name: slara
    depends_on:
      - io_avstats_db
    image: ioaero/slara:latest
    expose:
      - ${IO_AERO_STREAMLIT_SERVER_PORT}
    restart: always

  # ------------------------------------------------------------------------------
  # Nginx - Load Balancer.
  # ------------------------------------------------------------------------------
  load_balancer:
    container_name: load_balancer
    depends_on:
      - ae1982
      - pd1982
      - slara
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    image: nginx:stable-alpine
    ports:
      - ${IO_AERO_NGINX_CONNECTION_PORT}:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
