name: ioavstats
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - haversine
  - lat_lon_parser
  - mlxtend
  - numpy
  - openpyxl
  - pandas
  - plotly
  - psycopg2-binary
  - pyodbc
  - requests
  - sqlalchemy
  - streamlit
  - streamlit-pandas-profiling
  - tomli
  - tomli-w
  - virtualenv
  - xlrd
  - ydata-profiling
  - pip
  - pip:
    - git+https://IoAeroMachineUser:${PYPI_PAT}@github.com/io-aero/io-common.git
    - "matplotlib<=3.7"
    - pyeclat
