copyright: Copyright &copy;2022, IO-Aero.

exclude_docs: |
  how_to_compare_ntsb_and_io_db.md
  README.md
  release_schedule.md
extra:
  generator: false
extra_css:
  - assets/pymdownx-extras/extra-b1466b3f51.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-9e2c67b9.js

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - toc : {
    toc_depth: "1-3"
  }

nav:
  - Home: index.md
  - Setup:
    - Requirements: setup_requirements.md
    - Installation: setup_installation.md
    - Configuration:
      - IO-AVSTATS: config_io_avstats.md
      - Logging: config_logging.md
  - Operation: operation.md
  - Data:
      - Master Data Logs:
          - 1. Set up the database container: pre2008_01_s_d_c_23_08_21.md
          - 2. Create the database schema: pre2008_02_c_d_s_23_08_21.md
          - 3. Update the database schema: pre2008_03_u_d_s_23_08_21.md
          - 4. Load aviation occurrence categories: pre2008_11_a_o_c_23_08_21.md
          - 5. Load airport data: pre2008_12_l_a_p.md
          - 6. Load country and state data: pre2008_13_l_c_s_23_08_21.md
          - 7. Load sequence of events data: pre2008_14_l_s_e_23_08_21.md
          - 8. Load simplemaps data: pre2008_21_l_s_d_23_08_21.md
          - 9. Load ZIP Code Database data: pre2008_22_l_z_d.md
      - Transaction Data Logs:
          - 2024.01.08 up08JAN: 2024_01_08_log_up08JAN.md
          - 2024.01.01 up01JAN: 2024_01_01_log_up01JAN.md
          - 2024.01.01 avall: 2024_01_01_log_avall.md
          - 2023.12.22 up22DEC: 2023_12_22_log_up22DEC.md
          - 2023.12.15 up15DEC: 2023_12_15_log_up15DEC.md
          - 2023.12.08 up08DEC: 2023_12_08_log_up08DEC.md
          - 2023.12.01 up01DEC: 2023_12_04_log_up01DEC.md
          - 2023.12.01 avall: 2023_12_04_log_avall.md
          - 2023.11.22 up22NOV: 2023_11_22_log_up22NOV.md
          - 2023.11.15 up15NOV: 2023_11_15_log_up15NOV.md
          - 2023.11.08 up08NOV: 2023_11_08_log_up08NOV.md
          - 2023.11.01 up01NOV: 2023_11_01_log_up01NOV.md
          - 2023.11.01 avall: 2023_11_01_log_avall.md
          - 2023.10.22 up22OCT: 2023_10_22_log_up22OCT.md
          - 2023.10.15 up15OCT: 2023_10_15_log_up15OCT.md
          - 2023.10.08 up08OCT: 2023_10_08_log_up08OCT.md
          - 2023.10.01 up01OCT: 2023_10_01_log_up01OCT.md
          - 2023.10.01 avall: 2023_10_01_log_avall.md
  - Release Notes: release_notes.md
  - License: LICENSE.md

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            paths: [ioavstats]
            show_root_heading: false
            show_source: true
  - search

repo_name: GitHub
repo_url: https://github.com/io-aero/io-avstats

site_name: IO-AVSTATS - Aviation Event Statistics
site_url: https://io-aero.com/
site_description: Aviation Event Statistics
site_author: IO-Aero Team

theme:
  favicon: img/IO-Aero_1_Favicon.ico
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/IO-Aero_1_Logo.png
  name: material
  palette:
    primary: white
    accent: red

use_directory_urls: false
