copyright: Copyright &copy;2022, IO-Aero.

edit_uri: ""

extra:
  generator: false
extra_css:
  - assets/pymdownx-extras/extra-b1466b3f51.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-9e2c67b9.js

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - toc : {
    toc_depth: "1-3"
  }

nav:
  - Home: index.md
  - Setup:
    - Requirements: setup_requirements.md
    - Installation: setup_installation.md
    - Configuration:
      - IO-AVSTATS: config_io_avstats.md
      - Logging: config_logging.md
  - Operation: operation.md
  - Data Analysis:
      - Aviation Event Data Sets: data_analyis_ntsb_accident_data.md
      - DB Table io_ntsb_2002_2021: data_analyis_io_ntsb_2002_2021.md
      - DB View ae1982: data_analyis_ae1982.md
  - How to ...:
      - ... add NTSB accident files: how_to_add_ntsb_accident_files.md
      - ... create a new Streamlit app: how_to_create_new_streamlit_app.md
      - ... set up an AWS instance: how_to_setup_aws_instance.md
      - ... update IO-AVSTATS in AWS: how_to_update_avstats_on_aws.md
  - Release Documents:
    - Release Notes: release_notes.md
    - Release History: release_history.md
    - Release Schedule: release_schedule.md
    - Update Log Files:
        - 2023.01.22: update_log_2023_01_22.md
  - License: LICENSE.md

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            paths: [src/io_avstats]
            show_root_heading: false
            show_source: true
  - search

repo_name: GitHub
repo_url: https://github.com/io-aero/io-avstats

site_name: IO-AVSTATS - Aviation Event Statistics
site_url: https://io-aero.com/
site_description: Aviation Event Statistics
site_author: IO-Aero Team

theme:
  favicon: img/IO-Aero Logo.png
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/IO-Aero Logo.png
  name: material
  palette:
    primary: blue
    accent: red

use_directory_urls: false
