copyright: Copyright &copy;2022, IO-Aero.

exclude_docs: |
  how_to_compare_ntsb_and_io_db.md
  README.md
  release_schedule.md
extra:
  generator: false
extra_css:
  - assets/pymdownx-extras/extra-b1466b3f51.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-9e2c67b9.js

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - toc : {
    toc_depth: "1-3"
  }

nav:
  - Home: index.md
  - Setup:
    - Requirements: setup_requirements.md
    - Installation: setup_installation.md
    - Configuration:
      - IO-AVSTATS: config_io_avstats.md
      - Logging: config_logging.md
  - Operation: operation.md
  - How to ...:
      - ... add NTSB accident files: how_to_add_ntsb_accident_files.md
      - ... create a new Streamlit app: how_to_create_new_streamlit_app.md
      - ... set up an AWS instance: how_to_setup_aws_instance.md
      - ... update IO-AVSTATS in AWS: how_to_update_avstats_on_aws.md
  - Data:
      - Master Data Logs:
          - 1. Set up the database container: pre2008_01_s_d_c_23_08_21.md
          - 2. Create the database schema: pre2008_02_c_d_s_23_08_21.md
          - 3. Update the database schema: pre2008_03_u_d_s_23_08_21.md
          - 4. Load aviation occurrence categories: pre2008_11_a_o_c_23_08_21.md
          - 5. Load airport data: pre2008_12_l_a_p.md
          - 6. Load country and state data: pre2008_13_l_c_s_23_08_21.md
          - 7. Load sequence of events data: pre2008_14_l_s_e_23_08_21.md
          - 8. Load simplemaps data: pre2008_21_l_s_d_23_08_21.md
          - 9. Load ZIP Code Database data: pre2008_22_l_z_d.md
      - Transaction Data Logs:
          - up22SEP 2023.09.22: 2023_09_22_log_up22SEP.md
          - up15SEP 2023.09.15: 2023_09_15_log_up15SEP.md
          - up08SEP 2023.09.08: 2023_09_08_log_up08SEP.md
          - up01SEP 2023.09.01: 2023_09_01_log_up01SEP.md
          - avall   2023.09.01: 2023_09_01_log_avall.md
          - Pre2008 2023.08.21: 2023_08_21_log_Pre2008.md
          - up22JUL 2023.07.22: 2023_07_22_log_up22JUL.md
          - up15JUL 2023.07.15: 2023_07_15_log_up15JUL.md
          - up08JUL 2023.07.08: 2023_07_08_log_up08JUL.md
          - up01JUL 2023.07.01: 2023_07_01_log_up01JUL.md
          - avall   2023.07.01: 2023_07_01_log_avall.md
          - Pre2008 2023.06.20: 2023_06_20_log_Pre2008.md
          - up15JUN 2023.06.15: 2023_06_15_log_up15JUN.md
          - up08JUN 2023.06.08: 2023_06_08_log_up08JUN.md
          - up01JUN 2023.06.01: 2023_06_01_log_up01JUN.md
          - avall   2023.06.01: 2023_06_01_log_avall.md
          - up22MAY 2023.05.22: 2023_05_22_log_up22MAY.md
          - up15MAY 2023.05.15: 2023_05_15_log_up15MAY.md
          - up08MAY 2023.05.08: 2023_05_08_log_up08MAY.md
          - up01MAY 2023.05.01: 2023_05_01_log_up01MAY.md
          - avall   2023.05.01: 2023_05_01_log_avall.md
          - up22APR 2023.04.22: 2023_04_22_log_up22APR.md
          - up08APR 2023.04.15: 2023_04_15_log_up15APR.md
          - up08APR 2023.04.08: 2023_04_08_log_up08APR.md
          - avall   2023.04.01: 2023_04_03_log_avall.md
          - Pre2008 2020.09.30: 2023_02_01_log_Pre2008.md
  - Release Notes: release_notes.md
  - License: LICENSE.md

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            paths: [ioavstats]
            show_root_heading: false
            show_source: true
  - search

repo_name: GitHub
repo_url: https://github.com/io-aero/io-avstats

site_name: IO-AVSTATS - Aviation Event Statistics
site_url: https://io-aero.com/
site_description: Aviation Event Statistics
site_author: IO-Aero Team

theme:
  favicon: img/IO-Aero_1_Favicon.ico
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/IO-Aero_1_Logo.png
  name: material
  palette:
    primary: white
    accent: red

use_directory_urls: false
