[default]
is_verbose = true
postgres_connection_port = 5432
postgres_container_name = "io_avstats_container"
postgres_container_port = 5432
postgres_database_schema = "public"
postgres_dbname = "io_avstats_db"
postgres_dbname_admin = "postgres"
postgres_host = "localhost"
postgres_net = "io_avstats_net"
postgres_pgdata ="data/postgres"
postgres_user = "io_aero"
postgres_user_admin = "postgres"
postgres_version ="latest"
[dev]
[prod]
[test]
