[default]
check_value = "default"
correction_work_dir = "data/correction"
database_commit_size = 10000
download_chunk_size = 524288
download_file_aviation_occurrence_categories = "data/Aviation_Occurrence_Categories/aviation_occurrence_categories.xlsx"
download_file_countries_states_json = "data/Countries_States/countries_states.json"
download_file_faa_airports = "data/FAA_Airports/Airports.csv"
download_file_faa_npias = "data/FAA_Airports/NPIAS-2023-2027-Appendix-A.xlsx"
download_file_faa_runways = "data/FAA_Airports/Runways.csv"
download_file_main_phases_of_flight = "data/Main_Phases_of_Flight/main_phases_of_flight.xlsx"
download_file_sequence_of_events = "data/Sequence_of_Events/CICTT_SOE_MAP.csv"
download_file_simplemaps_us_cities = "data/simplemaps/uscities.xlsx"
download_file_simplemaps_us_zips = "data/simplemaps/uszips.xlsx"
download_file_zip_codes_org = "data/United States Zip Codes.org/zip_code_database.xls"
download_timeout = 10
download_url_ntsb_prefix = "https://data.ntsb.gov/avdata/FileDirectory/DownloadFile?fileID=C%3A%5Cavdata%5C"
download_work_dir = "data/download"
is_runtime_environment_local = true
is_verbose = true
max_deviation_latitude = 0.01
max_deviation_longitude = 0.01
odbc_connection_string = "DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ={filename};"
postgres_connection_port = 5432
postgres_container_name = "io_avstats_db"
postgres_database_schema = "public"
postgres_dbname = "io_aero_db"
postgres_dbname_admin = "postgres"
postgres_host = "localhost"
postgres_password_guest = "YL9CGphL58Rye3nUDopw"
postgres_pgdata ="data/postgres"
postgres_user = "io_aero"
postgres_user_admin = "postgres"
postgres_user_guest = "guest"
postgres_version = "16.3"
razorsql_jar_file_windows = "C:\\Program Files\\RazorSQL\\razorsql.jar"
razorsql_java_path_windows = "C:\\Program Files\\RazorSQL\\jre11\\bin\\java"
razorsql_profile = "IO-AVSTATS"
razorsql_reference_dir = "data/RazorSQL"
razorsql_reference_file = "2024.01.22_avall.sql"
terminal_area_distance_nmi = 5

[dev]

[prod]

[test]
check_value = "test"
correction_work_dir = "data/correction_test"
download_work_dir = "data/download_test"
download_file_faa_airports = "data/FAA_Airports/Airports_pytest.csv"
download_file_faa_npias = "data/FAA_Airports/NPIAS-2023-2027-Appendix-A_pytest.xlsx"
download_file_faa_runways = "data/FAA_Airports/Runways_pytest.csv"
download_file_simplemaps_us_cities = "data/simplemaps/uscities_pytest.xlsx"
download_file_simplemaps_us_zips = "data/simplemaps/uszips_pytest.xlsx"
download_file_zip_codes_org = "data/United States Zip Codes.org/zip_code_database_pytest.xls"
postgres_connection_port = 5433
postgres_container_name = "io_avstats_db_test"
postgres_pgdata ="data/postgres_test"
