# Copyright (c) 2022 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""

def initialise_logger() -> None: ...
def progress_msg(msg: str) -> None: ...
def streamlit_demo() -> str: ...
def terminate_fatal(error_msg: str) -> None: ...
def version() -> str: ...
