# Copyright (c) 2022 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""

def get_msaccess_cursor(filename: str) -> tuple: ...
def get_postgres_cursor() -> tuple: ...
def get_postgres_cursor_admin() -> tuple: ...
