# Copyright (c) 2022 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""
import logging.config

ARG_TASK: str = ...
ARG_TASK_DEMO: str = ...
ARG_TASK_VERSION: str = ...

# Error messages.
ERROR_00_901: str = ...

FILE_ENCODING_DEFAULT: str = ...

INFO_00_001: str = ...
INFO_00_002: str = ...
INFO_00_003: str = ...
INFO_00_004: str = ...
INFO_00_005: str = ...
INFO_00_006: str = ...
INFORMATION_NOT_YET_AVAILABLE: str = ...
IO_AVSTATS_VERSION: str = ...

LOCALE: str = ...
LOGGER_END: str = ...
LOGGER_NAME: str = ...
LOGGER_START: str = ...

logger: logging.Logger
