FROM python:3.10.10 as base

LABEL maintainer="IO-Aero"

ARG APP
ARG MODE
ARG SERVER_ADDRESS
ARG SERVER_PORT

ENV APP=${APP}
ENV MODE=${MODE}
ENV SERVER_PORT=${SERVER_PORT}
ENV SQLALCHEMY_SILENCE_UBER_WARNING=1

SHELL ["/bin/bash", "-c"]

EXPOSE ${SERVER_PORT}

WORKDIR /home

ADD ../tmp/docs/img/ ./docs/img/
ADD ../tmp/download/ ./download/

COPY ../Makefile ./
COPY ../config/.settings.io_avstats_4_dockerfile.toml ./config/.settings.io_avstats.toml
COPY ../config/Pipfile.${APP}                         ./Pipfile
COPY ../config/config.toml.${APP}                     ./.streamlit/config.toml
COPY ../config/secrets_4_dockerfile.toml              ./.streamlit/secrets.toml
COPY ../config/settings.io_avstats_4_dockerfile.toml  ./settings.io_avstats.toml
COPY ../data/latest_postgres.zip                      ./download/IO-AVSTATS-DB.zip
COPY ../docs/img/StockSnap_SLQQYN6CRR.jpg             ./docs/img
COPY ../src/ioavstats/${APP}.py                       ./${APP}.py
COPY ../src/ioavstats/utils.py                        ./utils.py

RUN make pipenv-prod

ENTRYPOINT pipenv run streamlit run ${APP}.py --server.port=${SERVER_PORT} -- --host Cloud --mode ${MODE}
