name: ioavstats
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - mlxtend
  - numpy
  - pandas
  - plotly
  - protobuf==3.20.*
  - psycopg2-binary
  - sqlalchemy
  - streamlit
  - streamlit-pandas-profiling
  - virtualenv
  - ydata-profiling
  - pip:
    - git+https://IoAeroMachineUser:${PYPI_PAT}@github.com/io-aero/io-common.git
    - pyeclat
