name: ioavstats
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - haversine
  - lat_lon_parser
  - mlxtend
  - numpy
  - openpyxl
  - pandas
  - plotly
  - psycopg2-binary
  - pyodbc
  - requests
  - scons
  - sqlalchemy
  - streamlit
  - streamlit-pandas-profiling
  - tomli
  - tomli-w
  - virtualenv
  - xlrd
  - ydata-profiling
  - pip:
    - git+https://IoAeroMachineUser:${PYPI_PAT}@github.com/io-aero/io-common.git
    - pyeclat
    # Development dependencies
    - bandit
    - coverage
    - coveralls
    - docformatter
    - furo
    - ipython
    - mypy
    - myst-parser
    - ordered-set
    - pandas-stubs
    - pylint
    - pytest
    - pytest-cov
    - pytest-deadfixtures
    - pytest-helpers-namespace
    - pytest-random-order
    - rinohtype
    - ruff
    - sphinx
    - sphinx-autoapi
    - types-psycopg2
    - types-toml
    - vulture
