# Copyright (c) 2022-2023 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""

def get_ae1982_app() -> None: ...
def get_ae1982_chart() -> None: ...
def get_pd1982_app() -> None: ...
def get_pd1982_data_profile() -> None: ...
def get_pd1982_details() -> None: ...
