# Copyright (c) 2022-2023 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""
from dynaconf import Dynaconf  # type: ignore
from psycopg2.extensions import connection
from sqlalchemy.engine import Engine

def get_args() -> tuple[str, str]: ...
def get_engine(settings: Dynaconf) -> Engine: ...
def get_postgres_connection() -> connection: ...
def has_access(
    host_cloud: bool, app_id: str
) -> tuple[str, dict[str, dict[str, list[str]]]]: ...
def present_about(pg_conn: connection, app_id: str) -> None: ...
