#!/bin/bash

set -e

# ------------------------------------------------------------------------------
#
# run_version_check.sh: Check the installed software versions.
#
# ------------------------------------------------------------------------------

exec &> >(tee -i run_version_check.log) 2>&1
sleep .1

date +"DATE TIME : %d.%m.%Y %H:%M:%S"
echo " "
echo "=============================================================================> Version asdf: "
echo " "
echo "Current version of asdf: $(asdf --version)"
echo " "
echo "=============================================================================> Version aws: "
echo " "
echo "Current version of aws: $(aws --version)"
echo " "
echo "=============================================================================> Version CMake: "
echo " "
echo "Current version of CMake: $(cmake --version)"
echo " "
echo "=============================================================================> Version cURL: "
echo " "
echo "Current version of cURL: $(curl --version)"
echo " "
echo "=============================================================================> Version DBeaver: "
echo " "
echo "Current version of DBeaver: $(${HOME_DBEAVER}/dbeaver -help)"
echo " "
echo "=============================================================================> Version Docker Desktop: "
echo " "
echo "Current version of Docker Desktop: $(docker version)"
echo " "
echo "=============================================================================> Version dos2unix: "
echo " "
echo "Current version of dos2unix: $(dos2unix --version)"
echo " "
echo "=============================================================================> Version GCC / G++: "
echo " "
echo "Current version of GCC: $(gcc --version)"
echo "Current version of G++: $(g++ --version)"
echo " "
echo "=============================================================================> Version Git: "
echo " "
echo "Current version of Git: $(git --version)"
echo " "
echo "=============================================================================> Version GNU Autoconf: "
echo " "
echo "Current version of GNU Autoconf: $(autoconf -V)"
echo " "
echo "=============================================================================> Version GNU Automake: "
echo " "
echo "Current version of GNU Automake: $(automake --version)"
echo " "
echo "=============================================================================> Version GNU Make: "
echo " "
echo "Current version of GNU Make: $(make --version)"
echo " "
echo "=============================================================================> Version Python3: "
echo " "
echo "Current version of Python3: $(python --version)"
echo " "
echo "Current version of pip3: $(pip --version || true)"
echo " "
echo "=============================================================================> Version Rasterio: "
echo " "
echo "Current version of Rust: $(rio --version)"
echo " "
echo "=============================================================================> Version Rust: "
echo " "
echo "Current version of Rust: $(rustc --version)"
echo " "
echo "=============================================================================> Version Ubuntu: "
echo " "
echo "Current version of Ubuntu: $(lsb_release -a)"
echo " "
echo "=============================================================================> Version Vim: "
echo " "
echo "Current version of Vim: $(vim --version)"
echo " "
echo "=============================================================================> Version Wget: "
echo " "
echo "Current version of Wget: $(wget --version)"
echo " "
echo "=============================================================================="

exit 0
