#!/bin/zsh

set -e

# ------------------------------------------------------------------------------
#
# run_version_check.zsh: Check the installed software versions.
#
# ------------------------------------------------------------------------------

exec &> >(tee -i run_version_check.log) 2>&1
sleep .1

date +"DATE TIME : %d.%m.%Y %H:%M:%S"
print "\n "
print "\n=============================================================================> Version asdf: "
print "\n "
print "\nCurrent version of asdf: $(asdf --version)"
print "\n "
print "\n=============================================================================> Version aws: "
print "\n "
print "\nCurrent version of aws: $(aws --version)"
print "\n "
print "\n=============================================================================> Version CMake: "
print "\n "
print "\nCurrent version of CMake: $(cmake --version)"
print "\n "
print "\n=============================================================================> Version cURL: "
print "\n "
print "\nCurrent version of cURL: $(curl --version)"
print "\n "
print "\n=============================================================================> Version DBeaver: "
print "\n "
print "\nCurrent version of DBeaver: $(${HOME_DBEAVER}/dbeaver -help)"
print "\n "
print "\n=============================================================================> Version Docker Desktop: "
print "\n "
print "\nCurrent version of Docker Desktop: $(docker version)"
print "\n "
print "\n=============================================================================> Version dos2unix: "
print "\n "
print "\nCurrent version of dos2unix: $(dos2unix --version)"
print "\n "
print "\n=============================================================================> Version GCC / G++: "
print "\n "
print "\nCurrent version of GCC: $(gcc --version)"
print "\nCurrent version of G++: $(g++ --version)"
print "\n "
print "\n=============================================================================> Version Git: "
print "\n "
print "\nCurrent version of Git: $(git --version)"
print "\n "
print "\n=============================================================================> Version GNU Autoconf: "
print "\n "
print "\nCurrent version of GNU Autoconf: $(autoconf -V)"
print "\n "
print "\n=============================================================================> Version GNU Automake: "
print "\n "
print "\nCurrent version of GNU Automake: $(automake --version)"
print "\n "
print "\n=============================================================================> Version GNU Make: "
print "\n "
print "\nCurrent version of GNU Make: $(make --version)"
print "\n "
print "\n=============================================================================> Version Python3: "
print "\n "
print "\nCurrent version of Python3: $(python3 --version)"
print "\n "
print "\nCurrent version of pip3: $(pip3 --version || true)"
print "\n "
print "\n=============================================================================> Version Rasterio: "
print "\n "
print "\nCurrent version of Rasterio: $(rio --version)"
print "\n "
print "\n=============================================================================> Version Rust: "
print "\n "
print "\nCurrent version of Rust: $(rustc --version)"
print "\n "
print "\n=============================================================================> Version Ubuntu: "
print "\n "
print "\nCurrent version of Ubuntu: $(lsb_release -a)"
print "\n "
print "\n=============================================================================> Version Vim: "
print "\n "
print "\nCurrent version of Vim: $(vim --version)"
print "\n "
print "\n=============================================================================> Version Wget: "
print "\n "
print "\nCurrent version of Wget: $(wget --version)"
print "\n "
print "\n=============================================================================="

exit 0
