[db_postgres]
dbname="io_aero_db"
host="localhost"
password="YL9CGphL58Rye3nUDopw"
port=5432
user="guest"

#[connections.io_avstats_db]
#database="io_avstats_db"
#dialect="postgresql"
#host="localhost"
#password="YL9CGphL58Rye3nUDopw"
#port=5432
#type="sql"
#username="guest"
