[db_postgres]
dbname="IO_AERO_db"
host="localhost"
password="YL9CGphL58Rye3nUDopw"
port=5432
user="guest"

#[connections.IO_AERO_db]
#database="IO_AERO_db"
#dialect="postgresql"
#host="localhost"
#password="YL9CGphL58Rye3nUDopw"
#port=5432
#type="sql"
#username="guest"
